#Publish all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

#Position Controller
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint1_link
  pid: {p: 700.0, i: 50, d: 70.0}
joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint2_link
  pid: {p: 700.0, i: 50, d: 70.0}
joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint3_link
  pid: {p: 700.0, i: 50, d: 70.0}