#Publish all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

#Position Controller
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint1_joint
  pid: {p: 20.0, i: 100, d: 5.0}
joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint2_joint
  pid: {p: 20.0, i: 100, d: 5.0}
joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint3_joint
  pid: {p: 20.0, i: 100, d: 5.0}